name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          process-only: 'prs'
          pr-comment: >
            This repository does not accept pull requests,
            see the CONTRIBUTING.md for details.
          skip-closed-pr-comment: true
          exclude-pr-labels: 'github_actions'
